/**
 * Datos geográficos: Países y ciudades principales
 */

export interface GeoData {
  [pais: string]: string[];
}

export const PAISES_Y_CIUDADES: GeoData = {
  Paraguay: [
    'Asunción',
    'Ciudad del Este',
    'Encarnación',
    'Pedro Juan Caballero',
    'Presidente Franco',
    'Salto del Guairá',
    'Hernandarias',
    'Itauguá',
    'Mariano Roque Alonso',
    'Lambaré',
    'San Lorenzo',
    'Luque',
    'Fernando de la Mora',
    'Capiatá',
    'Ñemby',
  ],
  Argentina: [
    'Buenos Aires',
    'Córdoba',
    'Rosario',
    'Mendoza',
    'La Plata',
    'Mar del Plata',
    'Salta',
    'Santa Fe',
    'San Juan',
    'Resistencia',
    'Neuquén',
    'Posadas',
    'Bahía Blanca',
    'Paraná',
    'Corrientes',
  ],
  Brasil: [
    'São Paulo',
    'Río de Janeiro',
    'Brasilia',
    'Salvador',
    'Fortaleza',
    'Belo Horizonte',
    'Manaos',
    'Curitiba',
    'Recife',
    'Porto Alegre',
    'Belém',
    'Goiânia',
    'Guarulhos',
    'Campinas',
    'Foz do Iguaçu',
  ],
  Uruguay: [
    'Montevideo',
    'Salto',
    'Paysandú',
    'Las Piedras',
    'Rivera',
    'Maldonado',
    'Tacuarembó',
    'Melo',
    'Mercedes',
    'Artigas',
    'Minas',
    'San José de Mayo',
    'Durazno',
    'Florida',
    'Colonia del Sacramento',
  ],
  Chile: [
    'Santiago',
    'Valparaíso',
    'Concepción',
    'La Serena',
    'Antofagasta',
    'Temuco',
    'Rancagua',
    'Talca',
    'Arica',
    'Chillán',
    'Iquique',
    'Puerto Montt',
    'Coquimbo',
    'Osorno',
    'Valdivia',
  ],
  'Estados Unidos': [
    'Nueva York',
    'Los Ángeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Filadelfia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San José',
    'Austin',
    'Jacksonville',
    'Fort Worth',
    'Columbus',
    'San Francisco',
    'Charlotte',
    'Indianapolis',
    'Seattle',
    'Denver',
    'Boston',
    'Miami',
  ],
  China: [
    'Pekín',
    'Shanghai',
    'Guangzhou',
    'Shenzhen',
    'Chongqing',
    'Tianjin',
    'Chengdu',
    'Nanjing',
    'Wuhan',
    'Xi\'an',
    'Hangzhou',
    'Dongguan',
    'Shenyang',
    'Qingdao',
    'Jinan',
  ],
  México: [
    'Ciudad de México',
    'Guadalajara',
    'Monterrey',
    'Puebla',
    'Tijuana',
    'León',
    'Juárez',
    'Zapopan',
    'Mérida',
    'San Luis Potosí',
    'Aguascalientes',
    'Hermosillo',
    'Saltillo',
    'Mexicali',
    'Culiacán',
  ],
  España: [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Sevilla',
    'Zaragoza',
    'Málaga',
    'Murcia',
    'Palma de Mallorca',
    'Las Palmas',
    'Bilbao',
    'Alicante',
    'Córdoba',
    'Valladolid',
    'Vigo',
    'Gijón',
  ],
  Colombia: [
    'Bogotá',
    'Medellín',
    'Cali',
    'Barranquilla',
    'Cartagena',
    'Cúcuta',
    'Soledad',
    'Ibagué',
    'Bucaramanga',
    'Soacha',
  ],
  Perú: [
    'Lima',
    'Arequipa',
    'Trujillo',
    'Chiclayo',
    'Piura',
    'Iquitos',
    'Cusco',
    'Huancayo',
    'Chimbote',
    'Pucallpa',
  ],
  Bolivia: [
    'Santa Cruz de la Sierra',
    'La Paz',
    'Cochabamba',
    'Sucre',
    'Oruro',
    'Tarija',
    'Potosí',
    'Trinidad',
    'Cobija',
    'Riberalta',
  ],
};

/**
 * Obtiene lista de países
 */
export const getPaises = (): string[] => {
  return Object.keys(PAISES_Y_CIUDADES).sort();
};

/**
 * Obtiene ciudades de un país
 */
export const getCiudadesPorPais = (pais: string): string[] => {
  return PAISES_Y_CIUDADES[pais] || [];
};

/**
 * Obtiene todas las ciudades (útil para búsqueda)
 */
export const getAllCiudades = (): string[] => {
  return Object.values(PAISES_Y_CIUDADES).flat().sort();
};
