create table detalle_pedido
(
    id              bigint generated by default as identity
        primary key,
    created_at      timestamp(6)   not null,
    deleted_at      timestamp(6),
    is_active       boolean,
    updated_at      timestamp(6),
    cantidad        integer        not null,
    precio_unitario numeric(15, 2) not null,
    sub_total       numeric(15, 2) not null,
    pedido_id       bigint         not null
        constraint fkg9h17fjynh9lgf1kbn0v9p4kf
            references pedidos,
    producto_id     bigint         not null
        constraint fkdfdl21316mnac14d7f4oi4m84
            references productos
);

